name: writing_tools
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  archive: ^3.4.10
  xml: ^6.5.0
  path: ^1.8.0
  pdf_text_extraction: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
